#!/usr/bin/env ruby
# Set CODE_SIGN_ENTITLEMENTS on the App target so the aps-environment
# entitlement (App/App.entitlements) is embedded in the signed binary.
# Uses the xcodeproj gem (shipped with CocoaPods) for a reliable edit rather
# than text-patching the pbxproj. Run on every CI build because ios/ is
# regenerated by `capacitor add ios`.
require 'xcodeproj'

project_path = 'ios/App/App.xcodeproj'
project = Xcodeproj::Project.open(project_path)

patched = 0
project.targets.each do |target|
  next unless target.name == 'App'
  target.build_configurations.each do |config|
    config.build_settings['CODE_SIGN_ENTITLEMENTS'] = 'App/App.entitlements'
    puts "Set CODE_SIGN_ENTITLEMENTS for #{config.name}"
    patched += 1
  end
end

if patched.zero?
  warn 'ERROR: App target not found; CODE_SIGN_ENTITLEMENTS not set'
  exit 1
end

project.save
puts "pbxproj saved (#{patched} configuration(s))"
