#!/usr/bin/env python3
"""Patch AppDelegate.swift for push notifications + icon-badge clearing.

1. Capacitor's @capacitor/push-notifications plugin needs the AppDelegate to
   forward Apple's APNs registration callbacks via NotificationCenter. The
   freshly generated Capacitor iOS project does NOT include these, so
   register() succeeds but no device token is ever delivered to JS.

2. Clear the app-icon badge when the app becomes active, so the red count
   disappears once the user opens the app. The default template ALREADY
   defines an (empty) applicationDidBecomeActive stub, so we inject into it
   rather than declaring a second one (that is a duplicate-method error).

Idempotent; run on every CI build because ios/ is regenerated by
`capacitor add ios`.
"""
import re
import sys

PATH = "ios/App/App/AppDelegate.swift"

with open(PATH, "r") as f:
    src = f.read()

changed = False

# Ensure UserNotifications is imported (needed for setBadgeCount)
if "import UserNotifications" not in src:
    src = re.sub(r"(import Capacitor)", r"\1\nimport UserNotifications", src, count=1)
    changed = True
    print("Added import UserNotifications")

# 1. APNs registration forwarding methods (absent from the default template)
PUSH_METHODS = """
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
    }

    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
    }
"""
if "didRegisterForRemoteNotificationsWithDeviceToken" not in src:
    m = re.search(r"class AppDelegate[^{]*\{", src)
    if not m:
        sys.stderr.write("ERROR: AppDelegate class declaration not found\n")
        sys.exit(1)
    src = src[:m.end()] + "\n" + PUSH_METHODS + src[m.end():]
    changed = True
    print("Added push registration forwarding methods")
else:
    print("Push methods already present")

# 2. Clear the icon badge inside the EXISTING applicationDidBecomeActive stub.
#    setBadgeCount is the non-deprecated API (iOS 16+); guarded so it compiles
#    against the iOS 14 deployment target without a deprecation warning.
if "setBadgeCount" not in src and "applicationIconBadgeNumber" not in src:
    badge = ("\n        if #available(iOS 16.0, *) {"
             "\n            UNUserNotificationCenter.current().setBadgeCount(0)"
             "\n        }")
    m = re.search(r"func applicationDidBecomeActive\(_\s+\w+:\s*UIApplication\)\s*\{", src)
    if m:
        src = src[:m.end()] + badge + src[m.end():]
        changed = True
        print("Injected badge clear into existing applicationDidBecomeActive")
    else:
        # No stub present (unexpected) — add a complete method
        m2 = re.search(r"class AppDelegate[^{]*\{", src)
        method = ("\n    func applicationDidBecomeActive(_ application: UIApplication) {"
                  + badge + "\n    }\n")
        src = src[:m2.end()] + method + src[m2.end():]
        changed = True
        print("Added applicationDidBecomeActive with badge clear")
else:
    print("Badge clear already present")

if changed:
    with open(PATH, "w") as f:
        f.write(src)
print("AppDelegate patch complete")
