#!/usr/bin/env python3
"""Inject AppDelegate methods needed for push notifications + icon badge.

1. Capacitor's @capacitor/push-notifications plugin relies on the host app's
   AppDelegate forwarding Apple's APNs registration callbacks via
   NotificationCenter. A freshly generated Capacitor iOS project does NOT
   include these methods, so PushNotifications.register() succeeds but neither
   the 'registration' nor 'registrationError' JS event ever fires (no device
   token is delivered).

2. applicationDidBecomeActive clears the app-icon badge number whenever the app
   is opened/resumed, so the red count on the icon disappears once the user
   opens the app to read (pushes set badge=1; nothing else clears it).

This script is idempotent and run on every CI build because the ios/ project
is regenerated by `capacitor add ios`.
"""
import re
import sys

PATH = "ios/App/App/AppDelegate.swift"

METHODS = """
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
    }

    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
        application.applicationIconBadgeNumber = 0
    }
"""

with open(PATH, "r") as f:
    src = f.read()

if "didRegisterForRemoteNotificationsWithDeviceToken" in src:
    print("AppDelegate already has remote-notification methods; nothing to do")
    sys.exit(0)

# Insert immediately after the opening brace of the AppDelegate class so the
# methods land inside the class regardless of the exact protocol list.
match = re.search(r"class AppDelegate[^{]*\{", src)
if not match:
    sys.stderr.write("ERROR: could not find AppDelegate class declaration\n")
    sys.exit(1)

insert_at = match.end()
patched = src[:insert_at] + "\n" + METHODS + src[insert_at:]

with open(PATH, "w") as f:
    f.write(patched)

print("AppDelegate patched with remote-notification forwarding methods")
