-- ═══════════════════════════════════════════════════════════════════════════
-- SOUQ v1b · PLAN THEMES  ·  APPLIED LIVE 2026-07-17 via MCP
-- ═══════════════════════════════════════════════════════════════════════════
-- Consumables (owner: "used for one time only, need more? earn more").
-- Full flow design: letsmeet2 resource/souq-decisions.md §8.2a.
--   buy in Souq → pocket COLLECTION → create-time pill applies to ONE plan →
--   CONSUMED PERMANENTLY. Owner ruling (same day): cancelling does NOT return
--   the theme — closes the cancel/re-dress loop (one purchase, infinite
--   themed plans). trg_souq_theme_on_cancel was applied live then DROPPED
--   (souq_themes_consumed_no_return).
--
-- Schema: plans.theme text (the key, e.g. 'desert_dusk') · user_perks widened
-- (perk like 'theme\_%', duration_days 0, applied_plan uuid) · souq_config
-- gains theme_prices (10 × 250) + theme_gate {"track":"host","need":3}.
--
-- RPCs (live defs are the authority; grants match the v1 set):
--   souq_buy_theme(key, req)   — idempotent (dup BEFORE balance, the v1
--       lesson), HOST-GATED at theme_gate.need. ⚠ DEBUG BYPASS: the creator
--       uuid skips the gate (nobody has 3 qualifying hosted plans yet, owner
--       included — he must be able to test). REMOVE once real users unlock.
--   souq_apply_theme(perk_id, plan_id) — owned+unspent theme, host-owned
--       uncancelled plan, plans.theme must be null (one theme per plan).
--   my_souq() v3 — adds theme_prices + theme_need; 'active' now filters to
--       glow perks so an applied theme can never masquerade as a glow.
--
-- Verified in rolled-back txns: buy (gate-bypassed) · dup req → {ok,dup} ·
-- apply to fake plan → BAD_PLAN · apply to own plan sets plans.theme ·
-- cancel → plans.theme null AND perk back in pocket (count checked).
--
-- Incidental discovery while testing: the owner's committed balance is 270,
-- not 470 — he has been buying glows ON DEVICE. The store works live.

-- ── 2026-07-18 PRE-LAUNCH: debug stripped ──────────────────────────────────
-- souq_buy_theme creator gate-bypass REMOVED (souq_remove_creator_theme_gate_
-- bypass) — themes are Host-3 for everyone now. Also cleared live: creator's
-- fake debug_grant points + the purchases they funded + seeded recent_plans
-- (balance back to a real 250). App-side hatches removed in letsmeet2 (tutorial
-- replay long-press, glow debug cycle, client gate-bypass mirror).
